TAP Compliance fixes
opencadc/dal pull request #80
Opened 2022-03-20 15:57 UTC by at88mph

This PR might be too big.  It includes the following changes:

- Updates for `NULL` values in Upload tables
- Include borrowed logic from Starjava to read `BINARY2`, `BINARY`, and `FITS` (Untested) `STREAM` data.
- Minor VOTable arraysize fixes (i.e. arraysize="1" interpretation)

The `BINARY` support approach was to have a separate implementation of the `TableData` interface as a `BinaryTableData` and set that when the appropriate tag under `DATA` is discovered.  If this is incorrect, please advise.

Even with these changes, there are still `WARNINGS` from `taplint` regarding `arraysize="1"`.  The EuroVO Registry does not seem to recognize DALI 1.1 due as the returned `timestamp` `xtype` from a `adql:TIMESTAMP` `xtype` is returned as an error.

2022-04-11 22:46 UTC, at88mph commented
Cherry picked classes from Starjava and persisted their packages.

2022-04-11 23:26 UTC, pdowler requested changes

2022-04-11 23:26 UTC, pdowler commented on cadc-dali/src/main/java/ca/nrc/cadc/dali/tables/votable/VOTableReader.java
> +                    if (format instanceof IntegerFormat || format instanceof ShortFormat
this can be removed? and the imports of these format classes

2022-04-11 23:26 UTC, pdowler commented on cadc-dali/src/main/java/ca/nrc/cadc/dali/util/IntegerFormat.java
> +            log.error("return null");
remove log message in *Format classes

2022-04-11 23:26 UTC, pdowler commented on cadc-dali/src/test/java/ca/nrc/cadc/dali/util/IntegerFormatTest.java
> +    @Test
this test also needed in SortFormatTest and LongFormatTest

2022-04-12 22:28 UTC, pdowler approved these changes

2022-04-12 22:28 UTC, merged